# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"NeptuneCallback": "00_callback.neptune.ipynb"}

modules = ["callback/neptune.py"]

doc_url = "https://fastai.github.io/fastai_neptune/"

git_url = "https://github.com/fastai/fastai_neptune/tree/master/"

def custom_doc_links(name): return None
